const {chromium} = require('/Users/meilinger/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert = require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
 const context=await browser.newContext({permissions:['clipboard-read','clipboard-write']});
 const page=await context.newPage(); const errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 const ready=()=>page.waitForFunction(()=>!document.querySelector('#keyword-filter').disabled && document.querySelector('#results-list').getAttribute('aria-busy')==='false');
 const reset=async()=>{await page.locator('#reset-filters').click();await ready()};
 const select=async(id,value)=>{
  const field=page.locator('[data-filter-dropdown]').filter({has:page.locator('#'+id)});
  await field.locator('button').first().click();
  await field.locator('[data-filter-value="'+value+'"]').click(); await ready();
 };
 await page.setViewportSize({width:1440,height:1000});
 await page.goto('http://127.0.0.1:8899'); await ready();
 await page.locator('#keyword-filter').fill('image');
 await page.locator('#keyword-filter').press('ArrowDown'); await page.locator('#keyword-filter').press('Enter');
 await page.waitForFunction(()=>document.querySelector('#paper-details').classList.contains('has-content'));
 assert.match(page.url(),/paper=/);
 await page.locator('[data-show-selection-in-results]').click();
 assert(await page.evaluate(()=>document.activeElement.classList.contains('result-item')));
 const revealed=await page.evaluate(()=>({top:document.activeElement.getBoundingClientRect().top,bottom:document.querySelector('.results-heading-row').getBoundingClientRect().bottom}));
 assert(revealed.top>=revealed.bottom-1,'Show in results covered by toolbar');
 console.log('paper autocomplete → Details → Show in results passed');
 await page.locator('#close-paper-details').click();
 const pin=await page.evaluate(()=>JSON.stringify(interactionState));
 assert.equal(await page.locator('#open-paper-details').getAttribute('aria-expanded'),'false');
 await page.locator('#open-paper-details').click();
 assert.equal(await page.evaluate(()=>JSON.stringify(interactionState)),pin);
 await page.goto('http://127.0.0.1:8899');await ready();
 const institution=await page.evaluate(()=>recordInstitution(visibleMarkerEntries[0].record));
 await page.locator('#keyword-filter').fill(institution);
 await page.locator('#keyword-suggestions [role="group"][aria-label="Institutions"] [role="option"]').first().click();
 assert(await page.locator('#paper-details').isVisible());
 console.log('institution autocomplete → marker/Details passed');
 await page.goto('http://127.0.0.1:8899');await ready();
 await select('published-only-filter','published-only');
 await page.locator('#more-filters-toggle').click();
 await select('preprint-filter','has-arxiv');
 await page.locator('#copy-view-link').click();
 const copied=await page.evaluate(()=>navigator.clipboard.readText());
 assert.match(copied,/published_only=1/);assert.match(copied,/version=has-arxiv/);
 await page.goto(copied);await ready();
 assert.equal(await page.locator('#published-only-filter').inputValue(),'published-only');
 assert.equal(await page.locator('#more-filters-toggle').getAttribute('aria-expanded'),'true');
 await page.locator('[data-remove-filter="published-only"]').click();await ready();
 const statusLabel=await page.locator('[data-filter-dropdown]').filter({has:page.locator('#published-only-filter')}).locator('button').first().innerText();
 assert.equal(statusLabel.trim(),'All','Publication Status chip leaves stale dropdown');
 await page.goBack();await ready();assert.equal(await page.locator('#published-only-filter').inputValue(),'published-only');
 await page.goForward();await ready();assert.equal(await page.locator('#published-only-filter').inputValue(),'all');
 await reset();
 await page.locator('#keyword-filter').fill('zzzznonezzzz');await ready();
 await page.waitForFunction(()=>!document.querySelector('#results-empty').hidden);
 await page.locator('#clear-empty-filters').click();await ready();
 assert.equal(await page.locator('#keyword-filter').inputValue(),'');
 await page.locator('[data-results-view="papers"]').click();await ready();
 await select('sort-control','title-asc');
 await page.locator('[data-results-view="institutions"]').click();await ready();
 assert.equal(await page.locator('#sort-control').inputValue(),'title-asc');
 console.log('filters/copy/reload/history/reset/zero recovery/view/sort passed');
 await page.goto('http://127.0.0.1:8899');await ready();
 await page.locator('[data-results-view="papers"]').click();await ready();
 await page.locator('#results-list .result-item').first().focus();
 assert(await page.locator('.is-card-cross-highlighted').count()>0);
 await page.locator('#copy-view-link').focus();
 assert.equal(await page.locator('.is-card-cross-highlighted').count(),0);
 const marker=page.locator('#map .leaflet-interactive').first();
 await marker.focus();await page.waitForTimeout(180);
 assert(await page.locator('.is-interaction-hovered').count()>0);
 await marker.press('Enter'); const state=await page.evaluate(()=>JSON.stringify(interactionState));
 await page.locator('#results-list .result-item').first().focus();
 assert.equal(await page.locator('.is-card-cross-highlighted').count(),0);
 assert.equal(await page.evaluate(()=>JSON.stringify(interactionState)),state);
 const help=page.locator('#map-help summary');await help.focus();await help.press('Enter');await help.press('Escape');
 assert.equal(await page.locator('#map-help').evaluate(e=>e.open),false);
 console.log('cross-highlighting, pin precedence, collapse/reopen and keyboard help passed');
 await page.locator('#keyword-filter').fill('zzzznonezzzz');await ready();
 assert.equal(await page.locator('#paper-details').isVisible(),false,'Empty Details must collapse when filters remove the selection');
 await page.goto('http://127.0.0.1:8899/?paper=missing-paper');await ready();
 assert.equal(await page.locator('#paper-details').isVisible(),true,'Unavailable deep link must open Details');
 assert.deepEqual(errors,[]);await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
