import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MAP_PATH = ROOT / "web/data/public_preview_map_data.json"
PAPER_PATH = ROOT / "web/data/public_preview_papers.json"
CANONICAL = "University of Naples Federico II"
FORBIDDEN = (
    "Federico II University Hospital",
    "University Hospital Federico II",
    "Federico II Hospital",
)
REGRESSION_TITLES = {
    "On The Detection of Synthetic Images Generated by Diffusion Models",
    "Raising the Bar of AI-generated Image Detection with CLIP",
    "Zero-Shot Detection of AI-Generated Images",
    (
        "Intriguing properties of synthetic images: from generative "
        "adversarial networks to diffusion models"
    ),
}


def _records(path):
    return json.loads(path.read_text(encoding="utf-8"))["records"]


def _author_names(record):
    return [
        author.get("name", "") if isinstance(author, dict) else str(author)
        for author in record.get("authors", [])
    ]


def _luisa_records(path):
    return [
        record
        for record in _records(path)
        if "Luisa Verdoliva" in _author_names(record)
    ]


def _institution_payload(record):
    return json.dumps(
        {
            "institution": record.get("institution"),
            "current_institution": record.get("current_institution"),
            "affiliations": record.get("affiliations"),
            "aggregated_institutions": record.get("aggregated_institutions"),
            "author_institution_affiliations": record.get(
                "author_institution_affiliations"
            ),
        },
        ensure_ascii=False,
    )


def test_luisa_verdoliva_not_hospital_marker():
    map_records = _luisa_records(MAP_PATH)
    paper_records = _luisa_records(PAPER_PATH)

    assert map_records
    assert paper_records
    for record in [*map_records, *paper_records]:
        payload = _institution_payload(record)
        assert not any(name.casefold() in payload.casefold() for name in FORBIDDEN)


def test_luisa_verdoliva_canonical_naples():
    records = _luisa_records(MAP_PATH)

    assert records
    for record in records:
        mapped_to_an_institution = any(
            "Luisa Verdoliva" in affiliation.get("authors", [])
            for affiliation in record.get("author_institution_affiliations", [])
        )
        if mapped_to_an_institution:
            assert CANONICAL in _institution_payload(record)


def test_luisa_verdoliva_regression_examples_and_current_marker_authors():
    records = _luisa_records(MAP_PATH)
    titles = {record["title"] for record in records}

    assert REGRESSION_TITLES <= titles
    for title in REGRESSION_TITLES:
        title_records = [record for record in records if record["title"] == title]
        assert any(record.get("institution") == CANONICAL for record in title_records)
        for record in title_records:
            current_authors = {
                author["name"]
                for author in record["authors"]
                if author["is_current_marker_author"]
            }
            assert current_authors == set(record["institution_authors"])
