"""Reviewed evidence and curation data for the bounded Tier 2 HIGH pass."""

from __future__ import annotations


def affiliation(institution: str, authors: list[str], raw: str) -> dict[str, object]:
    return {"institution": institution, "authors": authors, "raw": raw}


DECISIONS = [
    {
        "candidate_id": "audit:07f15e7e8a78398a",
        "primary_source": "https://openaccess.thecvf.com/content/ICCV2025/html/Song_Riemannian-Geometric_Fingerprints_of_Generative_Models_ICCV_2025_paper.html",
        "decisive_evidence": "Sections 3.1, 3.3, and 4.2/Table 3 define artifacts as deviations in generated samples, predict the source generator from an observed image, and evaluate attribution across four image datasets and 27 model architectures. No watermark, embedded signature, service call, or generator parameters are required.",
        "evidence_resolution_outcome": "EVIDENCE_CONFIRMS_SCOPE",
        "narrowed_scope_rationale": "Passive source-model attribution from naturally occurring image traces is in scope.",
        "identity_reconciliation_outcome": "MISSING_ADD",
        "doi": "10.1109/ICCV51701.2025.01063",
        "arxiv_id": "2506.22802",
        "openalex_id": "W4416507446",
        "identity_note": "No strong identifier, exact-title, author/year/venue, method/acronym, or active-exclusion match. ManiFPT is distinct prior work; bounded title similarity is approximately 0.729.",
    },
    {
        "candidate_id": "audit:0b72dded38f87a65",
        "primary_source": "https://proceedings.iclr.cc/paper_files/paper/2026/file/9c0efc0d84c263972af72bf70a2de533-Paper-Conference.pdf",
        "decisive_evidence": "Section 5.2.2 and Table 4 independently evaluate General Synthetic Image Detection beyond facial manipulation: a linear probe trained on Stable Diffusion 1.4 versus ImageNet is tested on eight GenImage generators and reaches 88.50% mean accuracy.",
        "evidence_resolution_outcome": "EVIDENCE_CONFIRMS_SCOPE",
        "narrowed_scope_rationale": "The separately measured general AIGC detector is broader than the face-focused MMI-DD pretraining corpus.",
        "identity_reconciliation_outcome": "MISSING_ADD",
        "doi": "",
        "arxiv_id": "",
        "openalex_id": "",
        "identity_note": "No identifier or exact-title match; MMI-DD and SD² are absent from the current corpus and active exclusions. The closest bounded title match is approximately 0.596 and is a different work.",
    },
    {
        "candidate_id": "audit:0dc47031ed0bccc5",
        "primary_source": "https://arxiv.org/html/2604.16083",
        "decisive_evidence": "Section 4.1 identifies the CAT-Net/MVSS-Net evaluation sets as CASIA splicing/copy-move, Columbia splicing, NIST16 composite manipulation, Coverage copy-move, and the tampered-image subset of IMD2020. Tables 1–2 contain no independently evaluated generative-edit or fully generated subset.",
        "evidence_resolution_outcome": "EVIDENCE_EXCLUDES_SCOPE",
        "narrowed_scope_rationale": "The evaluated protocols are classical manipulation only; generative-model motivation does not establish an in-scope experiment.",
        "identity_reconciliation_outcome": "",
        "doi": "10.48550/arXiv.2604.16083",
        "arxiv_id": "2604.16083",
        "openalex_id": "W7154960552",
        "identity_note": "Identity reconciliation is not applicable after the scope exclusion.",
    },
    {
        "candidate_id": "audit:202541800aaec592",
        "primary_source": "https://jhss.scholasticahq.com/article/156299-conditional-uncertainty-aware-political-deepfake-detection-with-stochastic-convolutional-neural-networks.pdf",
        "decisive_evidence": "Sections 3.1–3.5 define an image-level OpenFake subset with 2,000 authentic photographs and 2,000 AI-generated images from multiple generators, filtered for political actors, institutions, events, and discourse, with generator-disjoint out-of-distribution evaluation.",
        "evidence_resolution_outcome": "EVIDENCE_CONFIRMS_SCOPE",
        "narrowed_scope_rationale": "This is a passive real-versus-synthetic still-image detector in a specialized political domain, not a face- or video-only system.",
        "identity_reconciliation_outcome": "MISSING_ADD",
        "doi": "10.64336/001c.156299",
        "arxiv_id": "2602.10343",
        "openalex_id": "W7127885743",
        "identity_note": "DOI, arXiv, OpenAlex, normalized title, author/year/venue, and active-exclusion checks are clear. The closest bounded title match is approximately 0.663 and unrelated.",
    },
    {
        "candidate_id": "audit:46984fabc086b053",
        "primary_source": "https://doi.org/10.1007/978-3-032-37274-1_4",
        "decisive_evidence": "Section 5.1 states that all evaluation uses FaceForensics++ in-domain and Celeb-DF-v1 plus DFDCP cross-dataset; Sections 5.2–5.4 retain those facial-deepfake datasets, and Section 4.2 defines retrieval over authentic and manipulated faces.",
        "evidence_resolution_outcome": "EVIDENCE_EXCLUDES_SCOPE",
        "narrowed_scope_rationale": "The contribution is pure face-deepfake adaptation with no broader synthetic-image benchmark.",
        "identity_reconciliation_outcome": "",
        "doi": "10.1007/978-3-032-37274-1_4",
        "arxiv_id": "",
        "openalex_id": "W7211888972",
        "identity_note": "Identity reconciliation is not applicable after the scope exclusion.",
    },
    {
        "candidate_id": "audit:6880617d9c9040d4",
        "primary_source": "https://aclanthology.org/2026.acl-long.1405.pdf",
        "decisive_evidence": "Section 2/Table 1 uses only CelebAMask-HQ and FFHQ faces for face swap, facial-attribute editing, and facial-component inpainting; Appendix G filters SynthScars to facial manipulations. The report attributes visible facial regions and artifact descriptions, not a source generator.",
        "evidence_resolution_outcome": "EVIDENCE_EXCLUDES_SCOPE",
        "narrowed_scope_rationale": "Every substantive evaluation is facial manipulation, and “attribution” is an explanation report rather than passive source/model attribution.",
        "identity_reconciliation_outcome": "",
        "doi": "10.18653/v1/2026.acl-long.1405",
        "arxiv_id": "2412.19685",
        "openalex_id": "W4405903586",
        "identity_note": "Identity reconciliation is not applicable after the scope exclusion.",
    },
    {
        "candidate_id": "audit:854cc239481946ba",
        "primary_source": "https://doi.org/10.1007/s00138-026-01836-7",
        "decisive_evidence": "The abstract and experiments introduce DVID with 17,442 Stable Diffusion violent-scene images and 17,253 real images, report 98% accuracy and 97.8% average precision, and independently test cross-model/color robustness on DiffusionForensics.",
        "evidence_resolution_outcome": "EVIDENCE_CONFIRMS_SCOPE",
        "narrowed_scope_rationale": "The paper detects fully generated still-image scenes and is not restricted to face or identity manipulation.",
        "identity_reconciliation_outcome": "MISSING_ADD",
        "doi": "10.1007/s00138-026-01836-7",
        "arxiv_id": "",
        "openalex_id": "W7162851466",
        "identity_note": "DOI, OpenAlex, normalized title, DVID acronym, and exclusion checks are clear. A 2024 paper by the same authors has a different title, venue, DOI, and contribution.",
    },
    {
        "candidate_id": "audit:cf16307ced603a1d",
        "primary_source": "https://arxiv.org/html/2607.05434",
        "decisive_evidence": "Section III defines three passive image classifiers applied independently to 4,000 images. Table III reports their standalone results, and Table VIII reports watermark-free corroboration: two-classifier agreement lowers false-positive rate from 20.7% to 1.7%, while three-classifier agreement yields 0% observed false positives. SynthID is confined to a separate 400-image experiment.",
        "evidence_resolution_outcome": "EVIDENCE_CONFIRMS_SCOPE",
        "narrowed_scope_rationale": "The passive detector analysis and corroboration remain valid without watermark recovery.",
        "identity_reconciliation_outcome": "MISSING_ADD",
        "doi": "10.48550/arXiv.2607.05434",
        "arxiv_id": "2607.05434",
        "openalex_id": "W7167855108",
        "identity_note": "No strong identifier, normalized-title, author/year/venue, method/acronym, or active-exclusion match; bounded fuzzy results are unrelated.",
    },
    {
        "candidate_id": "audit:ea0d7f9972aa1b1c",
        "primary_source": "https://doi.org/10.1007/978-3-032-31927-2_7",
        "decisive_evidence": "The abstract and Section 4/Table 1 evaluate UniversalFakeDetect across 19 models: ProGAN, CycleGAN, BigGAN, StyleGAN, GauGAN, StarGAN, low-level/perceptual manipulations, LDM, GLIDE, and DALL·E. SPARK-IL reports 94.60% mean accuracy and cross-category generalization.",
        "evidence_resolution_outcome": "EVIDENCE_CONFIRMS_SCOPE",
        "narrowed_scope_rationale": "The passive detector substantively evaluates broad GAN and diffusion imagery in addition to face-swap and manipulation subsets.",
        "identity_reconciliation_outcome": "MISSING_ADD",
        "doi": "10.1007/978-3-032-31927-2_7",
        "arxiv_id": "2604.03833",
        "openalex_id": "W7172139314",
        "identity_note": "Final DOI, arXiv version, OpenAlex work, normalized title, SPARK-IL acronym, author/year/venue, and active-exclusion checks establish one missing work.",
    },
    {
        "candidate_id": "audit:f12e2be8d1320201",
        "primary_source": "https://doi.org/10.1007/s41060-026-01192-9",
        "decisive_evidence": "Sections 2.3, 3.1, 6.3, and the dataset synthesis cover passive detection of GAN- and diffusion-generated images, including CIFAKE, GenImage, ArtiFact, StyleGAN, ProGAN, Stable Diffusion, Midjourney, ADM, GLIDE, and cross-generator generalization.",
        "evidence_resolution_outcome": "EVIDENCE_CONFIRMS_SCOPE",
        "narrowed_scope_rationale": "The survey substantively covers current passive AI-generated-image detection rather than only legacy CGI or classical forgery.",
        "identity_reconciliation_outcome": "MISSING_ADD",
        "doi": "10.1007/s41060-026-01192-9",
        "arxiv_id": "",
        "openalex_id": "W7166514721",
        "identity_note": "DOI, OpenAlex, normalized title, author/year/venue, survey identity, and active-exclusion checks found no current representation.",
    },
    {
        "candidate_id": "audit:f293e205186b3f59",
        "primary_source": "https://openaccess.thecvf.com/content/ICCV2025/html/Zheng_Learning_Counterfactually_Decoupled_Attention_for_Open-World_Model_Attribution_ICCV_2025_paper.html",
        "decisive_evidence": "Section 2 distinguishes active injected fingerprints from passive attribution and identifies CDAL as passive. Section 4/Table 3 evaluates OSMA source labels over real images, 14 seen GAN classes, and 53 unseen GAN classes; OSMA includes ImageNet, LSUN, COCO, and Yosemite content beyond faces, while OW-DFA supplies face-swap and other generative-editing attacks.",
        "evidence_resolution_outcome": "EVIDENCE_CONFIRMS_SCOPE",
        "narrowed_scope_rationale": "CDAL attributes source generators from inherent visual traces and includes a substantive non-face benchmark without injected signatures.",
        "identity_reconciliation_outcome": "MISSING_ADD",
        "doi": "10.1109/ICCV51701.2025.00019",
        "arxiv_id": "2506.23074",
        "openalex_id": "W4416510385",
        "identity_note": "DOI, arXiv, OpenAlex, normalized title, CDAL acronym, author/year/venue, and active-exclusion checks found no current representation.",
    },
    {
        "candidate_id": "audit:f55fbb498b42444f",
        "primary_source": "https://doi.org/10.1007/s11263-024-02255-9",
        "decisive_evidence": "Sections 4–5 construct the 13-method, 100,000-images-per-method HiFi-IFDL benchmark spanning fully synthetic and partial images. Section 5.4 independently trains a ProGAN detector and tests 18 methods including Stable Diffusion, Sora, Midjourney, DALL·E 3, and InstantID while the main system evaluates image detection and localization.",
        "evidence_resolution_outcome": "EVIDENCE_CONFIRMS_SCOPE",
        "narrowed_scope_rationale": "CNN/diffusion-synthesized image detection is a substantive independent task within the unified detection/localization contribution.",
        "identity_reconciliation_outcome": "MISSING_ADD",
        "doi": "10.1007/s11263-024-02255-9",
        "arxiv_id": "2410.23556",
        "openalex_id": "W4405229107",
        "identity_note": "DOI, arXiv, OpenAlex, normalized title, HiFi-Net++/HiFi-IFDL method names, author/year/venue, and active-exclusion checks found no current representation.",
    },
]


PAPERS = [
    {
        "candidate_id": "audit:07f15e7e8a78398a",
        "title": "Riemannian-Geometric Fingerprints of Generative Models",
        "year": "2025",
        "authors": ["Hae Jin Song", "Laurent Itti"],
        "venue": "Proceedings of the IEEE/CVF International Conference on Computer Vision",
        "publication_type": "conference",
        "doi": "10.1109/ICCV51701.2025.01063",
        "arxiv_id": "2506.22802",
        "openalex_url": "https://openalex.org/W4416507446",
        "paper_url": "https://openaccess.thecvf.com/content/ICCV2025/html/Song_Riemannian-Geometric_Fingerprints_of_Generative_Models_ICCV_2025_paper.html",
        "code_url": "",
        "tasks": "source_attribution",
        "image_scopes": "fully_generated",
        "research_types": "method;analysis_study",
        "abstract": "This work defines artifacts and fingerprints of generative models using Riemannian geometry, presents a gradient-based algorithm for computing them from generated samples, and evaluates source-model attribution across four datasets, 27 model architectures, and vision and vision-language modalities.",
        "version_note": "The ICCV 2025 proceedings paper is canonical; arXiv 2506.22802 is its preprint version.",
        "affiliations": [affiliation("University of Southern California", ["Hae Jin Song", "Laurent Itti"], "USC Department of Computer Science")],
    },
    {
        "candidate_id": "audit:0b72dded38f87a65",
        "title": "A Rich Knowledge Space for Scalable Deepfake Detection",
        "year": "2026",
        "authors": ["Inho Jung", "Hyeongjun Choi", "Binh M. Le", "Hohyun Na", "Simon S. Woo"],
        "venue": "International Conference on Learning Representations",
        "publication_type": "conference",
        "doi": "",
        "arxiv_id": "",
        "openalex_url": "",
        "paper_url": "https://proceedings.iclr.cc/paper_files/paper/2026/hash/9c0efc0d84c263972af72bf70a2de533-Abstract-Conference.html",
        "code_url": "",
        "tasks": "detection",
        "image_scopes": "fully_generated;deepfake",
        "research_types": "method;dataset;benchmark",
        "abstract": "The paper introduces the 3.6-million-image MMI-DD facial deepfake collection and SD² detector. A separate general synthetic-image experiment trains a Stable Diffusion 1.4 versus ImageNet probe and evaluates eight GenImage generators, demonstrating transfer beyond facial manipulation.",
        "version_note": "The official ICLR 2026 proceedings paper, OpenReview hNd5L7WnjC, is the canonical work.",
        "affiliations": [affiliation("Sungkyunkwan University", ["Inho Jung", "Hyeongjun Choi", "Binh M. Le", "Hohyun Na", "Simon S. Woo"], "College of Computing and Informatics, Sungkyunkwan University, Suwon, Republic of Korea")],
    },
    {
        "candidate_id": "audit:202541800aaec592",
        "title": "Conditional uncertainty-aware political deepfake detection with stochastic Convolutional Neural Networks",
        "year": "2026",
        "authors": ["Rafael-Petruţ Gardoş"],
        "venue": "Journal of High School Science",
        "publication_type": "journal",
        "doi": "10.64336/001c.156299",
        "arxiv_id": "2602.10343",
        "openalex_url": "https://openalex.org/W7127885743",
        "paper_url": "https://doi.org/10.64336/001c.156299",
        "code_url": "",
        "tasks": "detection",
        "image_scopes": "fully_generated",
        "research_types": "method;analysis_study",
        "abstract": "This study evaluates deterministic and stochastic CNN inference for binary political-image classification on 2,000 authentic photographs and 2,000 AI-generated images selected from OpenFake, including controlled in-distribution and generator-disjoint out-of-distribution analysis.",
        "version_note": "The Journal of High School Science article is canonical; arXiv 2602.10343 is its preprint version.",
        "affiliations": [affiliation("Colegiul Național “Mihai Eminescu” Satu Mare", ["Rafael-Petruţ Gardoş"], "Colegiul National ”Mihai Eminescu” Satu Mare, Mihai Eminescu 5, 440014, Satu Mare, Romania")],
    },
    {
        "candidate_id": "audit:854cc239481946ba",
        "title": "Detecting violent deepfakes: dataset and a compact attention network with multi-scale supervision",
        "year": "2026",
        "authors": ["Surbhi Raj", "Jimson Mathew", "Arijit Mondal"],
        "venue": "Machine Vision and Applications",
        "publication_type": "journal",
        "doi": "10.1007/s00138-026-01836-7",
        "arxiv_id": "",
        "openalex_url": "https://openalex.org/W7162851466",
        "paper_url": "https://doi.org/10.1007/s00138-026-01836-7",
        "code_url": "https://github.com/surbhiraj786/Deepfake-Violent-Detection",
        "tasks": "detection",
        "image_scopes": "fully_generated",
        "research_types": "method;dataset;benchmark",
        "abstract": "The paper introduces DVID, with 17,442 Stable Diffusion violent-scene images and 17,253 real images, and a compact attention detector reporting 98% accuracy and 97.8% average precision, with additional cross-diffusion-model and color robustness tests.",
        "version_note": "The Machine Vision and Applications version of record is canonical; no separate preprint was established.",
        "affiliations": [affiliation("Indian Institute of Technology Patna", ["Surbhi Raj", "Jimson Mathew", "Arijit Mondal"], "Computer Science and Engineering, Indian Institute of Technology Patna, Patna, Bihar 801106, India")],
    },
    {
        "candidate_id": "audit:cf16307ced603a1d",
        "title": "Abductive Corroboration of Probabilistic AI Models for Forensic Synthetic Media Detection",
        "year": "2026",
        "authors": ["Junade Ali"],
        "venue": "arXiv",
        "publication_type": "preprint",
        "doi": "10.48550/arXiv.2607.05434",
        "arxiv_id": "2607.05434",
        "openalex_url": "https://openalex.org/W7167855108",
        "paper_url": "https://arxiv.org/abs/2607.05434",
        "code_url": "",
        "tasks": "detection",
        "image_scopes": "fully_generated",
        "research_types": "method;analysis_study",
        "abstract": "The study evaluates three passive synthetic-image classifiers on 2,000 GPT-Image-2 and 2,000 real Flickr images and measures how agreement among independent classifiers changes false-positive and true-positive performance. A separate SynthID experiment is not required for the passive results.",
        "version_note": "The current authoritative form is arXiv 2607.05434; no later formal publication was established.",
        "affiliations": [affiliation("The Alan Turing Institute", ["Junade Ali"], "The Alan Turing Institute, Defence and National Security Programme, London, United Kingdom")],
    },
    {
        "candidate_id": "audit:ea0d7f9972aa1b1c",
        "title": "SPARK-IL: Spectral Retrieval-Augmented RAG for Knowledge-Driven Deepfake Detection via Incremental Learning",
        "year": "2027",
        "authors": ["Hessen Bougueffa Eutamene", "Abdellah Zakaria Sellam", "Abdelmalik Taleb-Ahmed", "Abdenour Hadid"],
        "venue": "International Conference on Pattern Recognition",
        "publication_type": "conference",
        "doi": "10.1007/978-3-032-31927-2_7",
        "arxiv_id": "2604.03833",
        "openalex_url": "https://openalex.org/W7172139314",
        "paper_url": "https://doi.org/10.1007/978-3-032-31927-2_7",
        "code_url": "https://github.com/HessenUPHF/SPARK-IL",
        "tasks": "detection",
        "image_scopes": "fully_generated;generative_editing;deepfake",
        "research_types": "method",
        "abstract": "SPARK-IL combines dual-path spectral representations, retrieval-augmented classification, and incremental learning. On UniversalFakeDetect it evaluates 19 GAN, face-swap, low-level, perceptual, and diffusion generators and reports 94.60% mean accuracy.",
        "version_note": "The Springer ICPR proceedings chapter, published in the 2027 volume, is canonical; arXiv 2604.03833 is its preprint version.",
        "affiliations": [
            affiliation("Polytechnic University of Hauts-de-France", ["Hessen Bougueffa Eutamene", "Abdelmalik Taleb-Ahmed"], "Univ. Polytechnique Hauts-de-France, Valenciennes, France"),
            affiliation("Institute of Applied Sciences and Intelligent Systems", ["Abdellah Zakaria Sellam"], "Institute of Applied Sciences and Intelligent Systems – Lecce, Italy"),
            affiliation("University of Salento", ["Abdellah Zakaria Sellam"], "Department of Innovation Engineering, University of Salento, Italy"),
            affiliation("Sorbonne University Abu Dhabi", ["Abdenour Hadid"], "Sorbonne Center for Artificial Intelligence, Sorbonne University Abu Dhabi"),
        ],
    },
    {
        "candidate_id": "audit:f12e2be8d1320201",
        "title": "Deep learning for CGI and visual forgery detection: a comprehensive survey",
        "year": "2026",
        "authors": ["Ahmet Korkmaz", "Mustafa Özden"],
        "venue": "International Journal of Data Science and Analytics",
        "publication_type": "journal",
        "doi": "10.1007/s41060-026-01192-9",
        "arxiv_id": "",
        "openalex_url": "https://openalex.org/W7166514721",
        "paper_url": "https://doi.org/10.1007/s41060-026-01192-9",
        "code_url": "",
        "tasks": "detection",
        "image_scopes": "fully_generated",
        "research_types": "survey",
        "abstract": "This survey organizes deep-learning methods for CGI and visual-forgery detection across architectures, spatial/spectral/color representations, and multimodal fusion, with substantive coverage of modern GAN and diffusion detection, CIFAKE, GenImage, ArtiFact, and cross-generator generalization.",
        "version_note": "The International Journal of Data Science and Analytics version of record is canonical.",
        "affiliations": [
            affiliation("Turkish National Defense University", ["Ahmet Korkmaz"], "Army NCO Vocational HE School, Turkish National Defense University, Balıkesir, Turkey"),
            affiliation("Bursa Technical University", ["Mustafa Özden"], "Department of Electrical and Electronics Engineering, Bursa Technical University, 16310 Yıldırım, Bursa, Turkey"),
        ],
    },
    {
        "candidate_id": "audit:f293e205186b3f59",
        "title": "Learning Counterfactually Decoupled Attention for Open-World Model Attribution",
        "year": "2025",
        "authors": ["Yu Zheng", "Boyang Gong", "Fanye Kong", "Yueqi Duan", "Bingyao Yu", "Wenzhao Zheng", "Lei Chen", "Jiwen Lu", "Jie Zhou"],
        "venue": "Proceedings of the IEEE/CVF International Conference on Computer Vision",
        "publication_type": "conference",
        "doi": "10.1109/ICCV51701.2025.00019",
        "arxiv_id": "2506.23074",
        "openalex_url": "https://openalex.org/W4416510385",
        "paper_url": "https://openaccess.thecvf.com/content/ICCV2025/html/Zheng_Learning_Counterfactually_Decoupled_Attention_for_Open-World_Model_Attribution_ICCV_2025_paper.html",
        "code_url": "https://github.com/yzheng97/CDAL",
        "tasks": "source_attribution",
        "image_scopes": "fully_generated;generative_editing;deepfake",
        "research_types": "method",
        "abstract": "CDAL learns counterfactually decoupled attention for passive open-world source-model attribution. Experiments cover OW-DFA facial attacks and the broader OSMA GAN benchmark with real images, 14 seen source classes, and 53 unseen source classes.",
        "version_note": "The ICCV 2025 proceedings paper is canonical; arXiv 2506.23074 is its preprint version.",
        "affiliations": [affiliation("Tsinghua University", ["Yu Zheng", "Boyang Gong", "Fanye Kong", "Yueqi Duan", "Bingyao Yu", "Wenzhao Zheng", "Lei Chen", "Jiwen Lu", "Jie Zhou"], "Tsinghua University, China")],
    },
    {
        "candidate_id": "audit:f55fbb498b42444f",
        "title": "Language-Guided Hierarchical Fine-Grained Image Forgery Detection and Localization",
        "year": "2025",
        "authors": ["Xiao Guo", "Xiaohong Liu", "Iacopo Masi", "Xiaoming Liu"],
        "venue": "International Journal of Computer Vision",
        "publication_type": "journal",
        "doi": "10.1007/s11263-024-02255-9",
        "arxiv_id": "2410.23556",
        "openalex_url": "https://openalex.org/W4405229107",
        "paper_url": "https://doi.org/10.1007/s11263-024-02255-9",
        "code_url": "https://github.com/CHELSEA234/HiFi-IFDL",
        "tasks": "detection;localization",
        "image_scopes": "fully_generated;generative_editing;deepfake;traditional_manipulation",
        "research_types": "method;dataset;benchmark",
        "abstract": "HiFi-Net++ unifies image-level forgery detection and pixel-level localization across CNN/diffusion synthesis, facial manipulation, and conventional editing. The paper constructs HiFi-IFDL and separately evaluates general synthetic-image detection across ProGAN and 18 held-out generation methods.",
        "version_note": "The International Journal of Computer Vision article is canonical; arXiv 2410.23556 is its preprint version.",
        "affiliations": [
            affiliation("Michigan State University", ["Xiao Guo", "Xiaoming Liu"], "Department of Computer Science and Engineering, Michigan State University, USA"),
            affiliation("Shanghai Jiao Tong University", ["Xiaohong Liu"], "John Hopcroft Center for Computer Science, Shanghai Jiao Tong University, China"),
            affiliation("Sapienza University of Rome", ["Iacopo Masi"], "Department of Computer Science, Sapienza, University of Rome, Italy"),
        ],
    },
]


NEW_INSTITUTIONS = [
    {"name": "Colegiul Național “Mihai Eminescu” Satu Mare", "type": "other", "abbreviation": "", "city": "Satu Mare", "country": "Romania", "openalex_institution_id": "", "ror_id": ""},
    {"name": "The Alan Turing Institute", "type": "research_unit", "abbreviation": "", "city": "London", "country": "United Kingdom", "openalex_institution_id": "https://openalex.org/I4210128584", "ror_id": "https://ror.org/035dkdb55"},
    {"name": "Institute of Applied Sciences and Intelligent Systems", "type": "research_unit", "abbreviation": "ISASI", "city": "Lecce", "country": "Italy", "openalex_institution_id": "", "ror_id": ""},
    {"name": "University of Salento", "type": "university", "abbreviation": "", "city": "", "country": "Italy", "openalex_institution_id": "", "ror_id": ""},
    {"name": "Turkish National Defense University", "type": "university", "abbreviation": "", "city": "Balıkesir", "country": "Turkey", "openalex_institution_id": "", "ror_id": ""},
    {"name": "Bursa Technical University", "type": "university", "abbreviation": "BTU", "city": "Bursa", "country": "Turkey", "openalex_institution_id": "", "ror_id": ""},
]


EXISTING_INSTITUTIONS = {
    "University of Southern California": "institution:6432056cdf12bb16",
    "Sungkyunkwan University": "institution:e80b94c605da24ce",
    "Indian Institute of Technology Patna": "institution:a4e0e93fcd90b1c0",
    "Polytechnic University of Hauts-de-France": "institution:1e2fe2432a089705",
    "Sorbonne University Abu Dhabi": "institution:271362b3e1310a1c",
    "Tsinghua University": "institution:4ae45b121fe12e9c",
    "Michigan State University": "institution:cd887bf808040e61",
    "Shanghai Jiao Tong University": "institution:fccd5d0ac9cc52f9",
    "Sapienza University of Rome": "institution:977430a4473aa4b0",
}
