"""Primary-source decisions for the bounded Tier 2 NORMAL evidence pass."""

from __future__ import annotations


def affiliation(institution: str, authors: list[str], raw: str) -> dict[str, object]:
    return {"institution": institution, "authors": authors, "raw": raw}


DECISIONS = [
    {
        "candidate_id": "audit:29fa62c1fc9fd79d",
        "primary_source": "https://proceedings.iclr.cc/paper_files/paper/2025/hash/08f9de0232c0b485110237f6e6cf88f1-Abstract-Conference.html",
        "decisive_evidence": "Sections 3.1 and 4, Tables 5-6 and 10-11, separately evaluate still images in Set B and Set C. Set B includes SDXL, Kandinsky 2.1, and SDXL-Turbo imagery; Set C includes 20,000 Midjourney and 1,000 ArtGuru images. Table 11 reports image-source attribution separately from audio and video.",
        "evidence_resolution_outcome": "EVIDENCE_CONFIRMS_SCOPE",
        "narrowed_scope_rationale": "The paper independently benchmarks passive detection and source attribution for fully generated, non-face still images.",
    },
    {
        "candidate_id": "audit:2fa7c05b3b864bfe",
        "primary_source": "https://proceedings.iclr.cc/paper_files/paper/2026/hash/49b80bb0eddf1e12a262ab6dfda2fcf6-Abstract-Conference.html",
        "decisive_evidence": "Section 4/Table 1 marks AIGC among Omni-273k manipulation types across the unified domains. Section 5/Table 2 reports natural-image localization separately on CocoGlide, a 512-image GLIDE diffusion-editing test set; the appendix preserves the per-dataset split.",
        "evidence_resolution_outcome": "EVIDENCE_CONFIRMS_SCOPE",
        "narrowed_scope_rationale": "Generative editing is a substantive, independently scored localization condition, not merely a dataset annotation or architectural claim.",
    },
    {
        "candidate_id": "audit:305b25515850fed3",
        "primary_source": "https://openaccess.thecvf.com/content/ICCV2025/html/Nam_M2SFormer_Multi-Spectral_and_Multi-Scale_Attention_with_Edge-Aware_Difficulty_Guidance_for_ICCV_2025_paper.html",
        "decisive_evidence": "Section 4 and Tables 1-2 train on CASIAv2 or DIS25k and test CASIAv1, Columbia, IMD2020, CoMoFoD, In the Wild, and MISD. The paper identifies the evaluated forgery types as splicing and copy-move; DIS25k is a composition/splicing corpus, with no modern generative-edit subset or separate generative result.",
        "evidence_resolution_outcome": "EVIDENCE_EXCLUDES_SCOPE",
        "narrowed_scope_rationale": "The substantive experiments cover classical splicing, copy-move, and compositing only.",
    },
    {
        "candidate_id": "audit:3be864bb29fef423",
        "primary_source": "https://www.ecva.net/papers/eccv_2024/papers_ECCV/html/6023_ECCV_2024_paper.php",
        "decisive_evidence": "Section 4.1 and Tables 1-3 use CASIAv2, IMD2020, CAT-Net synthetic training data, CASIAv1, Coverage, DSO-1, NIST16, and MISD. The evaluated sets are classical copy-move/splicing/compositing benchmarks; no diffusion or other modern generative-edit subset is reported separately.",
        "evidence_resolution_outcome": "EVIDENCE_EXCLUDES_SCOPE",
        "narrowed_scope_rationale": "The primary experiments do not substantiate generatively edited or partially synthesized inputs.",
    },
    {
        "candidate_id": "audit:4f169a0ad566bd1d",
        "primary_source": "https://www.ecva.net/papers/eccv_2024/papers_ECCV/html/12164_ECCV_2024_paper.php",
        "decisive_evidence": "Section 4 identifies IEdit and MagicBrush as language-driven datasets with novel edits, distinct from CASIA, Coverage, Columbia, IMD2020, and NIST16. Table 3 independently reports IEdit accuracy/image F1 and MagicBrush pixel/image/combined F1 and IoU.",
        "evidence_resolution_outcome": "EVIDENCE_CONFIRMS_SCOPE",
        "narrowed_scope_rationale": "Instruction-guided generative editing is independently evaluated for detection and localization.",
    },
    {
        "candidate_id": "audit:5485e42ab03970ce",
        "primary_source": "https://papers.nips.cc/paper_files/paper/2024/hash/f280a398c243b5fdaa09f57ece880fc9-Abstract-Datasets_and_Benchmarks_Track.html",
        "decisive_evidence": "Sections 4.1-4.2 and Tables 3-4 define Protocol-MVSS and Protocol-CAT over CASIA, Fantastic Reality, IMD2020, NIST16, Columbia, Coverage, tamperedCOCO, and tamperedRAISE. Added transforms are OpenCV copy-move and inpainting, and the paper explicitly says IMDL does not pertain to purely generated images; no modern generative subset is scored.",
        "evidence_resolution_outcome": "EVIDENCE_EXCLUDES_SCOPE",
        "narrowed_scope_rationale": "The benchmark protocols are classical manipulation evaluations despite reusable general-purpose code.",
    },
    {
        "candidate_id": "audit:6338fbc2cd19a1bf",
        "primary_source": "https://openaccess.thecvf.com/content/CVPR2024/html/Qu_Towards_Modern_Image_Manipulation_Localization_A_Large-Scale_Dataset_and_Novel_CVPR_2024_paper.html",
        "decisive_evidence": "Sections 1 and 3/Table 1 define MIML as 123,150 manually forged web images made with tools such as Photoshop/GIMP and categorize the manipulations as copy-move, splicing, and removal. Tables 2-7 evaluate MIML and conventional IML sets without a modern generative-edit subset.",
        "evidence_resolution_outcome": "EVIDENCE_EXCLUDES_SCOPE",
        "narrowed_scope_rationale": "The word modern describes scale and method design; the evaluated forgeries remain manually created classical manipulations.",
    },
    {
        "candidate_id": "audit:67fabc63d5da6e37",
        "primary_source": "https://openaccess.thecvf.com/content/ICCV2023/html/Zhou_Pre-Training-Free_Image_Manipulation_Localization_through_Non-Mutually_Exclusive_Contrastive_Learning_ICCV_2023_paper.html",
        "decisive_evidence": "Section 4.1 and Tables 1-2 evaluate CASIA, NIST16, Columbia, Coverage, and DEFACTO. Those benchmarks cover splicing, copy-move, and exemplar-based object removal/inpainting; the paper reports no diffusion, text-guided, or other modern generative manipulation subset.",
        "evidence_resolution_outcome": "EVIDENCE_EXCLUDES_SCOPE",
        "narrowed_scope_rationale": "Patch-label design does not change the classical provenance of all five evaluated benchmarks.",
    },
    {
        "candidate_id": "audit:6de8f49b49f65330",
        "primary_source": "https://www.ecva.net/papers/eccv_2024/papers_ECCV/html/1688_ECCV_2024_paper.php",
        "decisive_evidence": "Section 4 and Tables 1-2 report quantitative results only on CASIA, Coverage, Columbia, NIST16, and IMD2020. CocoGlide diffusion edits and FaceShifter appear only in Figure 6 qualitative visualizations, with no separate detection or localization metric.",
        "evidence_resolution_outcome": "EVIDENCE_EXCLUDES_SCOPE",
        "narrowed_scope_rationale": "Generative examples are incidental qualitative illustrations rather than a substantive forensic evaluation.",
    },
    {
        "candidate_id": "audit:7aba8c4410d51d0a",
        "primary_source": "https://openaccess.thecvf.com/content/ICCV2023/html/Sun_SAFL-Net_Semantic-Agnostic_Feature_Learning_Network_with_Auxiliary_Plugins_for_Image_ICCV_2023_paper.html",
        "decisive_evidence": "Section 4 uses ProDEFACTO, PSBattles, and authentic images for pretraining and tests Columbia, Coverage, CASIA, NIST16, and IMD2020 in Tables 2 and 4. ProDEFACTO derives from classical splicing, copy-move, and exemplar-based inpainting; no modern generative-edit results are reported.",
        "evidence_resolution_outcome": "EVIDENCE_EXCLUDES_SCOPE",
        "narrowed_scope_rationale": "All substantive inputs are classical manipulations; synthetic pretraining does not by itself establish generative-image forensics.",
    },
    {
        "candidate_id": "audit:9089a0b84b74868b",
        "primary_source": "https://openaccess.thecvf.com/content/WACV2024/html/Tailanian_Diffusion_Models_Meet_Image_Counter-Forensics_WACV_2024_paper.html",
        "decisive_evidence": "Section 4/Table 1 applies the diffusion counter-forensic transformation to Korus, FAU, and Coverage images and attacks ZERO, Noiseprint, Splicebuster, TruFor, and related camera-pipeline/classical-tampering forensic methods. It does not attack a passive synthetic-image detector or benchmark synthetic-image evidence.",
        "evidence_resolution_outcome": "EVIDENCE_EXCLUDES_SCOPE",
        "narrowed_scope_rationale": "Diffusion is the counter-forensic reconstruction mechanism, while the protected forensic task is classical image manipulation/camera trace analysis.",
    },
    {
        "candidate_id": "audit:93f2de88b5a876c9",
        "primary_source": "https://openaccess.thecvf.com/content/CVPR2024/html/Li_UnionFormer_Unified-Learning_Transformer_with_Multi-View_Representation_for_Image_Manipulation_Detection_CVPR_2024_paper.html",
        "decisive_evidence": "Section 4.1 identifies CocoGlide and the new 512-image BDNIE set made with Blended Diffusion for text-driven natural-image editing. Tables 1-2 report per-dataset localization/detection results including CocoGlide, and the BDNIE results are discussed separately.",
        "evidence_resolution_outcome": "EVIDENCE_CONFIRMS_SCOPE",
        "narrowed_scope_rationale": "Diffusion-based local edits are substantive, independently evaluated inputs alongside classical manipulations.",
    },
    {
        "candidate_id": "audit:a06bf41dfd2ab933",
        "primary_source": "https://www.ijcai.org/proceedings/2025/152",
        "decisive_evidence": "Section 4/Table 1 evaluates CASIA, Coverage, Columbia, NIST16, and IMD2020 after pretraining on splicing, copy-move, and removal data; the detection experiment uses CASIA-D. No AI-generated region or modern generative-edit test set is independently evaluated.",
        "evidence_resolution_outcome": "EVIDENCE_EXCLUDES_SCOPE",
        "narrowed_scope_rationale": "Learnable frequency decomposition is an architecture feature, not evidence of generatively produced test inputs.",
    },
    {
        "candidate_id": "audit:b5b43c8e6e91325d",
        "primary_source": "https://proceedings.neurips.cc/paper_files/paper/2025/hash/e0e25d425450b6fc8e34380de71b3aee-Abstract-Conference.html",
        "decisive_evidence": "Sections 3 and 5/Table 8 identify AutoSplice as AIGC and COCOGlide as a 512-image diffusion-edit test set within the evaluation suite. Tables 1 and 9 report independent COCOGlide segmentation F1 results, including fixed-threshold and optimal-threshold scores; Table 6 includes it in ablation.",
        "evidence_resolution_outcome": "EVIDENCE_CONFIRMS_SCOPE",
        "narrowed_scope_rationale": "The method substantively localizes diffusion-generated edits with separate quantitative results.",
    },
    {
        "candidate_id": "audit:b666c0f0f497632a",
        "primary_source": "https://proceedings.iclr.cc/paper_files/paper/2026/hash/54130c88f35967381cb25ae8aaad1ebe-Abstract-Conference.html",
        "decisive_evidence": "Section 3 and Appendix A.3.4 define AI-Generated panels as whole-panel Image Inference Forgery or partial Targeted Region Editing, yielding 74 fully generated and 550 partially generated verified images. Appendix D.3/Table 14 separately reports accuracy, IoU, set F1, and exact-match results for the AI-Generated fraud type.",
        "evidence_resolution_outcome": "EVIDENCE_CONFIRMS_SCOPE",
        "narrowed_scope_rationale": "Fully generated and partially synthesized scientific images form a distinct, independently scored forensic task.",
    },
    {
        "candidate_id": "audit:bcd4cedccc0c34eb",
        "primary_source": "https://www.ijcai.org/proceedings/2025/218",
        "decisive_evidence": "Section 4.1 defines six test sets and identifies Auto as DALL-E 2 AIGIF and BSN as 2,500 BrushNet diffusion edits; DID also spans ten inpainting methods. Table 1 reports F1/IoU separately for Auto and BSN, including ForgDiffuser scores of .9768/.9577 and .8358/.7527.",
        "evidence_resolution_outcome": "EVIDENCE_CONFIRMS_SCOPE",
        "narrowed_scope_rationale": "The tested forgery inputs, independently of the diffusion decoder, include substantial diffusion-generated local edits.",
    },
    {
        "candidate_id": "audit:ced0c9f8fe10fbb9",
        "primary_source": "https://openaccess.thecvf.com/content/CVPR2024/html/Yu_DiffForensics_Leveraging_Diffusion_Prior_to_Image_Forgery_Detection_and_Localization_CVPR_2024_paper.html",
        "decisive_evidence": "Section 4.1 explicitly separates six traditional-editing datasets from AutoSplice and OpenForensics, which it identifies as deep-generative-model forgeries. Table 2 reports pixel F1/AUC on both DGM sets, and Table 3 separately reports AutoSplice image-level accuracy/AUC/EER.",
        "evidence_resolution_outcome": "EVIDENCE_CONFIRMS_SCOPE",
        "narrowed_scope_rationale": "Deep-generative manipulations are substantive, independently scored detection/localization inputs beyond the detector's diffusion prior.",
    },
    {
        "candidate_id": "audit:e094e552be6fbe85",
        "primary_source": "https://openaccess.thecvf.com/content/ICCV2023/html/Ji_Uncertainty-guided_Learning_for_Improving_Image_Manipulation_Detection_ICCV_2023_paper.html",
        "decisive_evidence": "Section 4.1 and Tables 1-3 train on CASIAv2 and evaluate CASIAv1, NIST16, Columbia, and Coverage. The experiments cover conventional splicing/copy-move/compositing; references to synthetic pretraining concern competitor weights, with no independently evaluated AI-generated or generatively edited set.",
        "evidence_resolution_outcome": "EVIDENCE_EXCLUDES_SCOPE",
        "narrowed_scope_rationale": "Uncertainty modeling is evaluated only on conventional manipulation benchmarks.",
    },
    {
        "candidate_id": "audit:fa8eef7eb10763d0",
        "primary_source": "https://openaccess.thecvf.com/content/ICCV2025/html/Wong_ADCD-Net_Robust_Document_Image_Forgery_Localization_via_Adaptive_DCT_Feature_ICCV_2025_paper.html",
        "decisive_evidence": "Section 4 and Table 1 train on DocTamper and test its Test split plus FCD and SCD, with recompression and distortion robustness. Deep inpainting appears only in motivation/related work; the paper provides no generative-AI document-edit subset or separate result.",
        "evidence_resolution_outcome": "EVIDENCE_EXCLUDES_SCOPE",
        "narrowed_scope_rationale": "The substantive experiments concern conventional document tampering and post-processing robustness.",
    },
    {
        "candidate_id": "audit:fed41b0363b5f8c1",
        "primary_source": "https://openaccess.thecvf.com/content/ICCV2023/html/Zhai_Towards_Generic_Image_Manipulation_Detection_with_Weakly-Supervised_Self-Consistency_Learning_ICCV_2023_paper.html",
        "decisive_evidence": "Section 4 identifies GIER and IEdit as recent language-driven editing datasets whose manipulations are not constrained to copy-move, splicing, or inpainting. Table 3 independently reports image-level AUC/F1 on each set, both zero-shot and after image-label fine-tuning.",
        "evidence_resolution_outcome": "EVIDENCE_CONFIRMS_SCOPE",
        "narrowed_scope_rationale": "Language-guided generative edits receive a dedicated quantitative detection evaluation.",
    },
]


for decision in DECISIONS:
    decision.setdefault("identity_reconciliation_outcome", "")
    decision.setdefault("doi", "")
    decision.setdefault("arxiv_id", "")
    decision.setdefault("openalex_id", "")
    decision.setdefault("identity_note", "Identity reconciliation has not yet been performed.")


IDENTITIES = {
    "audit:29fa62c1fc9fd79d": {
        "doi": "",
        "arxiv_id": "",
        "openalex_id": "",
        "identity_note": "The official ICLR record supplies no DOI, arXiv ID, or OpenAlex work. The normalized title, complete author list, ILLUSION acronym, 2025 venue, bounded fuzzy matches, and active exclusions were checked against the 657-paper baseline; no representation was found.",
    },
    "audit:2fa7c05b3b864bfe": {
        "doi": "",
        "arxiv_id": "2411.14823",
        "openalex_id": "W4404987440",
        "identity_note": "The ICLR title is the final form of arXiv 2411.14823 / OpenAlex W4404987440, whose earlier title was 'Omni-IML: Towards Unified Image Manipulation Localization'. Final and alternate titles, authors, venue, Omni-IML acronym, identifiers, fuzzy matches, and exclusions found no current representation.",
    },
    "audit:4f169a0ad566bd1d": {
        "doi": "10.1007/978-3-031-73223-2_15",
        "arxiv_id": "",
        "openalex_id": "W4404124998",
        "identity_note": "DOI, OpenAlex ID, normalized title, authors/year/venue, the INR method description, bounded fuzzy matches, and active exclusions found no current representation.",
    },
    "audit:93f2de88b5a876c9": {
        "doi": "10.1109/CVPR52733.2024.01190",
        "arxiv_id": "",
        "openalex_id": "W4402727697",
        "identity_note": "DOI, OpenAlex ID, normalized title, authors/year/venue, UnionFormer/BDNIE names, bounded fuzzy matches, and active exclusions found no current representation.",
    },
    "audit:b5b43c8e6e91325d": {
        "doi": "10.52202/085713-5121",
        "arxiv_id": "2411.19466",
        "openalex_id": "W4405030341",
        "identity_note": "The NeurIPS 2025 paper and arXiv 2411.19466 are one work. DOI, arXiv ID, OpenAlex ID, normalized title, authors/venue, ForgerySleuth/ForgeryAnalysis names, bounded fuzzy matches, and active exclusions found no current representation.",
    },
    "audit:b666c0f0f497632a": {
        "doi": "",
        "arxiv_id": "2603.25089",
        "openalex_id": "W7141348801",
        "identity_note": "The ICLR 2026 proceedings paper and arXiv 2603.25089 are one work. ArXiv/OpenAlex IDs, normalized title, authors/year/venue, THEMIS acronym, bounded fuzzy matches, and active exclusions found no current representation.",
    },
    "audit:bcd4cedccc0c34eb": {
        "doi": "10.24963/ijcai.2025/218",
        "arxiv_id": "",
        "openalex_id": "W4414359990",
        "identity_note": "DOI, OpenAlex ID, normalized title, authors/year/venue, ForgDiffuser acronym, bounded fuzzy matches, and active exclusions found no current representation.",
    },
    "audit:ced0c9f8fe10fbb9": {
        "doi": "10.1109/CVPR52733.2024.01213",
        "arxiv_id": "",
        "openalex_id": "W4402715936",
        "identity_note": "DOI, OpenAlex ID, normalized title, authors/year/venue, DiffForensics acronym, bounded fuzzy matches, and active exclusions found no current representation.",
    },
    "audit:fed41b0363b5f8c1": {
        "doi": "10.1109/ICCV51070.2023.02046",
        "arxiv_id": "2309.01246",
        "openalex_id": "W4390872411",
        "identity_note": "The ICCV 2023 paper and arXiv 2309.01246 are one work. DOI, arXiv ID, OpenAlex ID, normalized title, authors/year/venue, WSCL acronym, bounded fuzzy matches, and active exclusions found no current representation.",
    },
}

for decision in DECISIONS:
    identity = IDENTITIES.get(decision["candidate_id"])
    if identity:
        decision.update(identity)
        decision["identity_reconciliation_outcome"] = "MISSING_ADD"


PAPERS = [
    {
        "candidate_id": "audit:29fa62c1fc9fd79d",
        "title": "ILLUSION: Unveiling Truth with a Comprehensive Multi-Modal, Multi-Lingual Deepfake Dataset",
        "year": "2025",
        "authors": ["Kartik Thakral", "Rishabh Ranjan", "Akanksha Singh", "Akshat Jain", "Mayank Vatsa", "Richa Singh"],
        "venue": "International Conference on Learning Representations",
        "publication_type": "conference",
        "doi": "",
        "arxiv_id": "",
        "openalex_url": "",
        "paper_url": "https://proceedings.iclr.cc/paper_files/paper/2025/hash/08f9de0232c0b485110237f6e6cf88f1-Abstract-Conference.html",
        "code_url": "https://www.iab-rubric.org/illusion-database",
        "tasks": "detection;source_attribution",
        "image_scopes": "fully_generated;deepfake",
        "research_types": "dataset;benchmark;analysis_study",
        "abstract": "ILLUSION is a 1.3-million-sample multimodal and multilingual deepfake dataset spanning images, audio, video, and synchronized media. Its still-image protocols separately benchmark detection and source attribution on text-to-image systems, synthetic faces, and real-world Midjourney and ArtGuru images.",
        "version_note": "The official ICLR 2025 proceedings paper is canonical; no DOI, arXiv record, or OpenAlex work was established.",
        "affiliations": [
            affiliation("Indian Institute of Technology Jodhpur", ["Kartik Thakral", "Rishabh Ranjan", "Akanksha Singh", "Akshat Jain", "Mayank Vatsa", "Richa Singh"], "IIT Jodhpur, India"),
            affiliation("Indian Institute of Science Education and Research Bhopal", ["Akanksha Singh"], "IISER Bhopal, India"),
        ],
    },
    {
        "candidate_id": "audit:2fa7c05b3b864bfe",
        "title": "Omni-IML: Towards Unified Interpretable Image Manipulation Localization",
        "year": "2026",
        "authors": ["Chenfan Qu", "Yiwu Zhong", "Fengjun Guo", "Lianwen Jin"],
        "venue": "International Conference on Learning Representations",
        "publication_type": "conference",
        "doi": "",
        "arxiv_id": "2411.14823",
        "openalex_url": "https://openalex.org/W4404987440",
        "paper_url": "https://proceedings.iclr.cc/paper_files/paper/2026/hash/49b80bb0eddf1e12a262ab6dfda2fcf6-Abstract-Conference.html",
        "code_url": "https://github.com/qcf-568/OmniIML",
        "tasks": "localization",
        "image_scopes": "generative_editing;deepfake;traditional_manipulation",
        "research_types": "method;dataset",
        "abstract": "Omni-IML is a generalist localization model spanning natural images, documents, faces, and scene text, together with the Omni-273k interpretation dataset. Its natural-image protocol independently evaluates GLIDE diffusion edits in CocoGlide alongside classical manipulation benchmarks.",
        "version_note": "The ICLR 2026 proceedings paper is canonical; arXiv 2411.14823 uses the earlier title 'Omni-IML: Towards Unified Image Manipulation Localization'.",
        "affiliations": [
            affiliation("South China University of Technology", ["Chenfan Qu", "Lianwen Jin"], "South China University of Technology"),
            affiliation("Peking University", ["Yiwu Zhong"], "Peking University"),
            affiliation("IntSig Information Co. Ltd", ["Fengjun Guo"], "INTSIG Information Co., Ltd."),
            affiliation("INTSIG-SCUT Joint Lab on Document Analysis and Recognition", ["Fengjun Guo", "Lianwen Jin"], "INTSIG-SCUT Joint Lab on Document Analysis and Recognition"),
        ],
    },
    {
        "candidate_id": "audit:4f169a0ad566bd1d",
        "title": "Image Manipulation Detection With Implicit Neural Representation and Limited Supervision",
        "year": "2024",
        "authors": ["Zhenfei Zhang", "Mingyang Li", "Xin Li", "Ming-Ching Chang", "Jun-Wei Hsieh"],
        "venue": "European Conference on Computer Vision",
        "publication_type": "conference",
        "doi": "10.1007/978-3-031-73223-2_15",
        "arxiv_id": "",
        "openalex_url": "https://openalex.org/W4404124998",
        "paper_url": "https://doi.org/10.1007/978-3-031-73223-2_15",
        "code_url": "",
        "tasks": "detection;localization",
        "image_scopes": "generative_editing;traditional_manipulation",
        "research_types": "method",
        "abstract": "This work combines implicit-neural-representation preprocessing with weakly supervised and unsupervised manipulation detection. In addition to conventional benchmarks, it independently evaluates instruction-guided edits from IEdit and MagicBrush with image- and pixel-level metrics.",
        "version_note": "The ECCV 2024 Springer proceedings chapter is canonical; no separate arXiv version was established.",
        "affiliations": [
            affiliation("University at Albany, State University of New York", ["Zhenfei Zhang", "Xin Li", "Ming-Ching Chang"], "University at Albany, State University of New York"),
            affiliation("Stanford University", ["Mingyang Li"], "Stanford University"),
            affiliation("National Yang Ming Chiao Tung University", ["Jun-Wei Hsieh"], "National Yang Ming Chiao Tung University"),
        ],
    },
    {
        "candidate_id": "audit:93f2de88b5a876c9",
        "title": "UnionFormer: Unified-Learning Transformer with Multi-View Representation for Image Manipulation Detection and Localization",
        "year": "2024",
        "authors": ["Shuaibo Li", "Wei Ma", "Jianwei Guo", "Shibiao Xu", "Benchong Li", "Xiaopeng Zhang"],
        "venue": "Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition",
        "publication_type": "conference",
        "doi": "10.1109/CVPR52733.2024.01190",
        "arxiv_id": "",
        "openalex_url": "https://openalex.org/W4402727697",
        "paper_url": "https://openaccess.thecvf.com/content/CVPR2024/html/Li_UnionFormer_Unified-Learning_Transformer_with_Multi-View_Representation_for_Image_Manipulation_Detection_CVPR_2024_paper.html",
        "code_url": "",
        "tasks": "detection;localization",
        "image_scopes": "generative_editing;traditional_manipulation",
        "research_types": "method;dataset",
        "abstract": "UnionFormer unifies object, RGB, and noise views for concurrent image-manipulation detection and localization. Its evaluation includes CocoGlide diffusion edits and the paper's 512-image BDNIE set generated with Blended Diffusion for text-driven natural-image editing.",
        "version_note": "The CVPR 2024 proceedings paper is canonical; no separate preprint was established.",
        "affiliations": [
            affiliation("Beijing University of Technology", ["Shuaibo Li", "Wei Ma", "Benchong Li"], "Beijing University of Technology"),
            affiliation("Institute of Automation, Chinese Academy of Sciences", ["Shuaibo Li", "Jianwei Guo", "Xiaopeng Zhang"], "MAIS, Institute of Automation, Chinese Academy of Sciences"),
            affiliation("Beijing University of Posts and Telecommunications", ["Shibiao Xu"], "Beijing University of Posts and Telecommunications"),
        ],
    },
    {
        "candidate_id": "audit:b5b43c8e6e91325d",
        "title": "ForgerySleuth: Empowering Multimodal Large Language Models for Image Manipulation Detection",
        "year": "2025",
        "authors": ["Zhihao Sun", "Haoran Jiang", "Haoran Chen", "Yixin Cao", "Xipeng Qiu", "Zuxuan Wu", "Yu-Gang Jiang"],
        "venue": "Advances in Neural Information Processing Systems",
        "publication_type": "conference",
        "doi": "10.52202/085713-5121",
        "arxiv_id": "2411.19466",
        "openalex_url": "https://openalex.org/W4405030341",
        "paper_url": "https://proceedings.neurips.cc/paper_files/paper/2025/hash/e0e25d425450b6fc8e34380de71b3aee-Abstract-Conference.html",
        "code_url": "https://github.com/sunzhihao18/ForgerySleuth",
        "tasks": "detection;localization",
        "image_scopes": "generative_editing;traditional_manipulation",
        "research_types": "method;dataset",
        "abstract": "ForgerySleuth combines a multimodal language model, trace encoder, and vision decoder to explain and segment manipulated regions, and introduces the ForgeryAnalysis dataset. It reports separate localization results on diffusion-edited COCOGlide and includes AutoSplice AIGC inputs.",
        "version_note": "The NeurIPS 2025 proceedings paper is canonical; arXiv 2411.19466 is its preprint version.",
        "affiliations": [
            affiliation("Fudan University", ["Zhihao Sun", "Haoran Jiang", "Haoran Chen", "Yixin Cao", "Xipeng Qiu", "Zuxuan Wu", "Yu-Gang Jiang"], "Shanghai Key Lab of Intelligent Information Processing, School of Computer Science, Fudan University"),
            affiliation("Shanghai Collaborative Innovation Center of Intelligent Visual Computing", ["Zhihao Sun", "Haoran Jiang", "Haoran Chen", "Yixin Cao", "Xipeng Qiu", "Zuxuan Wu", "Yu-Gang Jiang"], "Shanghai Collaborative Innovation Center of Intelligent Visual Computing"),
        ],
    },
    {
        "candidate_id": "audit:b666c0f0f497632a",
        "title": "THEMIS: Towards Holistic Evaluation of MLLMs for Scientific Paper Fraud Forensics",
        "year": "2026",
        "authors": ["Tzu-Yen Ma", "Bo Zhang", "Zichen Tang", "Junpeng Ding", "Haolin Tian", "Yuanze Li", "Zhuodi Hao", "Zixin Ding", "Zirui Wang", "Xinyu Yu", "Shiyao Peng", "Yizhuo Zhao", "Ruomeng Jiang", "Yiling Huang", "Peizhi Zhao", "Jiayuan Chen", "Weisheng Tan", "Haocheng Gao", "Yang Liu", "Jiacheng Liu", "Zhongjun Yang", "Jiayu Huang", "Haihong E"],
        "venue": "International Conference on Learning Representations",
        "publication_type": "conference",
        "doi": "",
        "arxiv_id": "2603.25089",
        "openalex_url": "https://openalex.org/W7141348801",
        "paper_url": "https://proceedings.iclr.cc/paper_files/paper/2026/hash/54130c88f35967381cb25ae8aaad1ebe-Abstract-Conference.html",
        "code_url": "https://github.com/BUPT-Reasoning-Lab/THEMIS",
        "tasks": "detection;localization",
        "image_scopes": "fully_generated;generative_editing;traditional_manipulation",
        "research_types": "dataset;benchmark;analysis_study",
        "abstract": "THEMIS benchmarks multimodal language models on scientific-paper fraud across seven image scenarios and five fraud types. Its AI-Generated category separately evaluates entirely generated panels and targeted generative edits with classification, localization, and set-based metrics.",
        "version_note": "The ICLR 2026 proceedings paper is canonical; arXiv 2603.25089 is its preprint version.",
        "affiliations": [
            affiliation("Beijing University of Posts and Telecommunications", ["Tzu-Yen Ma", "Bo Zhang", "Zichen Tang", "Junpeng Ding", "Haolin Tian", "Yuanze Li", "Zhuodi Hao", "Zixin Ding", "Zirui Wang", "Xinyu Yu", "Shiyao Peng", "Yizhuo Zhao", "Ruomeng Jiang", "Yiling Huang", "Peizhi Zhao", "Jiayuan Chen", "Weisheng Tan", "Haocheng Gao", "Yang Liu", "Jiacheng Liu", "Zhongjun Yang", "Jiayu Huang", "Haihong E"], "Beijing University of Posts and Telecommunications"),
        ],
    },
    {
        "candidate_id": "audit:bcd4cedccc0c34eb",
        "title": "ForgDiffuser: General Image Forgery Localization with Diffusion Models",
        "year": "2025",
        "authors": ["Mengxi Wang", "Shaozhang Niu", "Jiwei Zhang"],
        "venue": "Thirty-Fourth International Joint Conference on Artificial Intelligence",
        "publication_type": "conference",
        "doi": "10.24963/ijcai.2025/218",
        "arxiv_id": "",
        "openalex_url": "https://openalex.org/W4414359990",
        "paper_url": "https://www.ijcai.org/proceedings/2025/218",
        "code_url": "",
        "tasks": "localization",
        "image_scopes": "generative_editing;traditional_manipulation",
        "research_types": "method",
        "abstract": "ForgDiffuser conditions a diffusion decoder on forged images to generate localization masks. Its six-dataset evaluation separately reports localization on DALL-E 2 AutoSplice and BrushNet diffusion edits as well as traditional manipulation sets.",
        "version_note": "The IJCAI 2025 proceedings paper is canonical; no separate preprint was established.",
        "affiliations": [
            affiliation("Beijing University of Posts and Telecommunications", ["Mengxi Wang", "Shaozhang Niu", "Jiwei Zhang"], "Beijing Key Lab of Intelligent Telecommunication Software and Multimedia, Beijing University of Posts and Telecommunications, China; Key Laboratory of Interactive Technology and Experience System, Ministry of Culture and Tourism (BUPT), China"),
            affiliation("Southeast Digital Economy Development Institute", ["Shaozhang Niu"], "Southeast Digital Economy Development Institute, China"),
        ],
    },
    {
        "candidate_id": "audit:ced0c9f8fe10fbb9",
        "title": "DiffForensics: Leveraging Diffusion Prior to Image Forgery Detection and Localization",
        "year": "2024",
        "authors": ["Zeqin Yu", "Jiangqun Ni", "Yuzhen Lin", "Haoyi Deng", "Bin Li"],
        "venue": "Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition",
        "publication_type": "conference",
        "doi": "10.1109/CVPR52733.2024.01213",
        "arxiv_id": "",
        "openalex_url": "https://openalex.org/W4402715936",
        "paper_url": "https://openaccess.thecvf.com/content/CVPR2024/html/Yu_DiffForensics_Leveraging_Diffusion_Prior_to_Image_Forgery_Detection_and_Localization_CVPR_2024_paper.html",
        "code_url": "",
        "tasks": "detection;localization",
        "image_scopes": "generative_editing;deepfake;traditional_manipulation",
        "research_types": "method",
        "abstract": "DiffForensics combines frozen semantic features, denoising-diffusion pretraining, and edge-cue enhancement for image-level detection and pixel-level localization. Its evaluation separates traditional edits from deep-generative AutoSplice and OpenForensics inputs.",
        "version_note": "The CVPR 2024 proceedings paper is canonical; no separate preprint was established.",
        "affiliations": [
            affiliation("Sun Yat-sen University", ["Zeqin Yu", "Jiangqun Ni"], "School of Computer Science and Engineering, Sun Yat-sen University; School of Cyber Science and Technology, Sun Yat-sen University"),
            affiliation("Peng Cheng Laboratory", ["Jiangqun Ni"], "Department of New Networks, Peng Cheng Laboratory"),
            affiliation("Shenzhen University", ["Yuzhen Lin", "Haoyi Deng", "Bin Li"], "Guangdong Key Laboratory of Intelligent Information Processing, Shenzhen University"),
        ],
    },
    {
        "candidate_id": "audit:fed41b0363b5f8c1",
        "title": "Towards Generic Image Manipulation Detection with Weakly-Supervised Self-Consistency Learning",
        "year": "2023",
        "authors": ["Yuanhao Zhai", "Tianyu Luan", "David Doermann", "Junsong Yuan"],
        "venue": "Proceedings of the IEEE/CVF International Conference on Computer Vision",
        "publication_type": "conference",
        "doi": "10.1109/ICCV51070.2023.02046",
        "arxiv_id": "2309.01246",
        "openalex_url": "https://openalex.org/W4390872411",
        "paper_url": "https://openaccess.thecvf.com/content/ICCV2023/html/Zhai_Towards_Generic_Image_Manipulation_Detection_with_Weakly-Supervised_Self-Consistency_Learning_ICCV_2023_paper.html",
        "code_url": "",
        "tasks": "detection;localization",
        "image_scopes": "generative_editing;traditional_manipulation",
        "research_types": "method",
        "tasks_evidence": "Section 4 and Table 4 report pixel-level manipulation localization with Pixel-Level F1, combined image/pixel F1, and qualitative localization maps across five datasets.",
        "abstract": "WSCL learns weakly supervised image-level manipulation detection and produces localization maps using multi-source and inter-patch consistency. It independently evaluates language-driven editing on GIER and IEdit, both before and after image-label fine-tuning.",
        "version_note": "The ICCV 2023 proceedings paper is canonical; arXiv 2309.01246 is its preprint version.",
        "affiliations": [
            affiliation("University at Buffalo", ["Yuanhao Zhai", "Tianyu Luan", "David Doermann", "Junsong Yuan"], "University at Buffalo"),
        ],
    },
]


NEW_INSTITUTIONS = [
    {"name": "Indian Institute of Technology Jodhpur", "type": "university", "abbreviation": "IIT Jodhpur", "city": "Jodhpur", "country": "India", "openalex_institution_id": "", "ror_id": ""},
    {"name": "Indian Institute of Science Education and Research Bhopal", "type": "university", "abbreviation": "IISER Bhopal", "city": "Bhopal", "country": "India", "openalex_institution_id": "", "ror_id": ""},
    {"name": "INTSIG-SCUT Joint Lab on Document Analysis and Recognition", "type": "research_unit", "abbreviation": "", "city": "", "country": "", "openalex_institution_id": "", "ror_id": ""},
    {"name": "Shanghai Collaborative Innovation Center of Intelligent Visual Computing", "type": "research_unit", "abbreviation": "", "city": "Shanghai", "country": "", "openalex_institution_id": "", "ror_id": ""},
    {"name": "Southeast Digital Economy Development Institute", "type": "research_unit", "abbreviation": "", "city": "", "country": "China", "openalex_institution_id": "", "ror_id": ""},
]


EXISTING_INSTITUTIONS = {
    "South China University of Technology": "institution:3e9b289ae248f660",
    "Peking University": "institution:46e4866d3b2954ab",
    "IntSig Information Co. Ltd": "institution:4be06805ebaa0400",
    "University at Albany, State University of New York": "institution:c121cd267550901f",
    "Stanford University": "institution:ed72534d79b73fac",
    "National Yang Ming Chiao Tung University": "institution:b99e56fd55395250",
    "Beijing University of Technology": "institution:f060d61d546153f2",
    "Institute of Automation, Chinese Academy of Sciences": "institution:966ff12833f90bb0",
    "Beijing University of Posts and Telecommunications": "institution:1502cb7c96ae3095",
    "Fudan University": "institution:baa1df7c4adddbda",
    "Sun Yat-sen University": "institution:5c85faa51cc57a24",
    "Peng Cheng Laboratory": "institution:aee00ab2f1fd8132",
    "Shenzhen University": "institution:ad9c8964d01f80d8",
    "University at Buffalo": "institution:612630c2527bff83",
}
